FOBJECTS += mod_grrhd_ppm.t mod_grrhd_phys.t mod_grrhd.t

#mod_grrhd_phys is splitted into the following parts
FOBJECTS +=	mod_grrhd_phys_parameters.t \
		mod_grrhd_phys_convert.t \
		mod_grrhd_phys_flux.t \
		mod_grrhd_phys_add_source.t
