FOBJECTS += mod_gremhd_ppm.t mod_gremhd_phys.t mod_gremhd.t

#mod_gremhd_phys is splitted into the following parts
FOBJECTS +=	mod_gremhd_phys_parameters.t \
		mod_gremhd_phys_convert.t \
		mod_gremhd_phys_flux.t \
		mod_gremhd_phys_add_source.t \
		mod_gremhd_phys_implicit_update.t \
		mod_gremhd_phys_divb_mg.t
