FOBJECTS += mod_grhd_ccsn_ppm.t mod_grhd_ccsn_phys.t mod_grhd_ccsn.t

#mod_grhd_ccsn_phys is splitted into the following parts
FOBJECTS +=	mod_grhd_ccsn_phys_parameters.t \
		mod_grhd_ccsn_phys_convert.t \
		mod_grhd_ccsn_phys_flux.t \
		mod_grhd_ccsn_phys_add_source.t \
		mod_grhd_ccsn_phys_one_d_core.t
