FOBJECTS += mod_grhd_ccsn_ILEAS_mpi_ppm.t mod_grhd_ccsn_ILEAS_mpi_phys.t mod_grhd_ccsn_ILEAS_mpi.t mod_grhd_ccsn_ILEAS_mpi_ILEAS.t

#mod_grhd_ccsn_ILEAS_mpi_phys is splitted into the following parts
FOBJECTS +=	mod_grhd_ccsn_ILEAS_mpi_phys_parameters.t \
		mod_grhd_ccsn_ILEAS_mpi_phys_convert.t \
		mod_grhd_ccsn_ILEAS_mpi_phys_flux.t \
		mod_grhd_ccsn_ILEAS_mpi_phys_add_source.t \
		mod_grhd_ccsn_ILEAS_mpi_phys_one_d_core.t
