FOBJECTS += mod_grhd_ccsn_leakage_ppm.t mod_grhd_ccsn_leakage_phys.t mod_grhd_ccsn_leakage.t mod_grhd_ccsn_leakage_simple_leakage.t

#mod_grhd_ccsn_leakage_phys is splitted into the following parts
FOBJECTS +=	mod_grhd_ccsn_leakage_phys_parameters.t \
		mod_grhd_ccsn_leakage_phys_convert.t \
		mod_grhd_ccsn_leakage_phys_flux.t \
		mod_grhd_ccsn_leakage_phys_add_source.t \
		mod_grhd_ccsn_leakage_phys_one_d_core.t
