FOBJECTS += mod_grhd_ppm.t mod_grhd_phys.t mod_grhd.t

#mod_grhd_phys is splitted into the following parts
FOBJECTS +=	mod_grhd_phys_parameters.t \
		mod_grhd_phys_convert.t \
		mod_grhd_phys_flux.t \
		mod_grhd_phys_add_source.t \
		mod_grhd_phys_one_d_core.t
