FOBJECTS += mod_grmhd_ppm.t mod_grmhd_phys.t mod_grmhd.t

#mod_grmhd_phys is splitted into the following parts
FOBJECTS +=	mod_grmhd_phys_parameters.t \
		mod_grmhd_phys_convert.t \
		mod_grmhd_phys_flux.t \
		mod_grmhd_phys_add_source.t \
		mod_grmhd_phys_divb_mg.t \
		mod_grmhd_phys_divb_ct.t
